# Generated by Django 4.1.7 on 2023-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.CharField(default='fara meniu', max_length=100),
            preserve_default=False,
        ),
    ]
