# Generated by Django 4.1.7 on 2023-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.CharField(default='Vlad Stan', max_length=50),
            preserve_default=False,
        ),
    ]
